version: '3.8'
services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: edutech-users-ms

  courses:
    build:
      context: ./curso
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: edutech-courses-ms

  evaluation:
    build:
      context: ./evaluacion
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: edutech-evaluation-ms

  enrollment:
    build:
      context: ./inscripcion
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    container_name: edutech-enrollment-ms